import { Link } from 'react-router-dom'
import { LegalLayout, Section } from '@/components/legal/LegalLayout'
import { usePageMeta } from '@/hooks/usePageMeta'

export function TermsPage() {
  usePageMeta({
    title: 'Terms of Service — MyRecruiterCheck',
    description: 'The terms that govern your use of MyRecruiterCheck.',
    path: '/terms',
  })

  return (
    <LegalLayout title="Terms of Service" updated="7 August 2026">
      <Section title="1. Introduction">
        <p>
          These Terms of Service ("Terms") govern your access to and use of MyRecruiterCheck (the
          "Service"), operated from the Netherlands. By creating an account or using the Service,
          you agree to these Terms. If you do not agree, do not use the Service.
        </p>
      </Section>

      <Section title="2. The Service">
        <p>
          MyRecruiterCheck lets you upload a CV and a job description to receive AI generated
          feedback, an interview probability score, and, on paid plans, a tailored CV, cover
          letter, and email for a recruiter. Outputs are generated automatically and are provided
          for informational purposes only; MyRecruiterCheck does not guarantee interviews, job
          offers, or any particular outcome from using the Service.
        </p>
      </Section>

      <Section title="3. Accounts">
        <p>
          You must provide accurate information when creating an account and keep your login
          credentials secure. You are responsible for all activity that occurs under your account.
          You must be at least 16 years old to use the Service.
        </p>
      </Section>

      <Section title="4. Subscriptions, Fees & Payment">
        <p>
          Paid plans are billed in advance on a recurring basis (weekly or monthly, as selected at
          checkout) via our payment processor, Stripe. Subscriptions renew automatically at the
          end of each billing period until cancelled. Prices are shown in EUR and may include
          applicable taxes.
        </p>
      </Section>

      <Section title="5. No Refunds">
        <p>
          All payments are final. MyRecruiterCheck does not offer refunds or credits for partial
          billing periods, unused checks, or dissatisfaction with generated results, except where
          required by mandatory law. You can cancel at any time to stop future renewals; your
          plan remains active until the end of the current billing period.
        </p>
      </Section>

      <Section title="6. Cancellation & Termination">
        <p>
          You may cancel your subscription at any time from the billing portal, and you may delete
          your account at any time from your Account settings. We may suspend or terminate your
          access if you breach these Terms or misuse the Service.
        </p>
      </Section>

      <Section title="7. Acceptable Use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Upload content you do not have the right to share, or that infringes another person's rights;</li>
          <li>Use the Service to build a competing product or to scrape or reverse engineer it;</li>
          <li>Attempt to disrupt, overload, or gain unauthorized access to the Service;</li>
          <li>Use the Service for any unlawful purpose.</li>
        </ul>
      </Section>

      <Section title="8. Your Content">
        <p>
          You retain ownership of the CV, job descriptions, and other content you submit ("Your
          Content"). You grant MyRecruiterCheck a limited license to process Your Content, including
          sending it to our AI provider, solely to operate and improve the Service for you. See
          our <Link to="/privacy" className="font-medium text-blue hover:underline">Privacy Policy</Link> for
          details on how your data is handled.
        </p>
      </Section>

      <Section title="9. AI Generated Content">
        <p>
          Feedback, scores, and documents are generated by an AI model and may contain errors or
          inaccuracies. Review all generated documents before submitting them to an employer.
          MyRecruiterCheck is not responsible for decisions made based on AI generated output.
        </p>
      </Section>

      <Section title="10. Intellectual Property">
        <p>
          The Service, including its design, code, and branding, is owned by MyRecruiterCheck and
          protected by intellectual property laws. These Terms do not grant you any rights to our
          trademarks or branding.
        </p>
      </Section>

      <Section title="11. Third Party Services">
        <p>
          The Service relies on third party providers, including Supabase (hosting, database,
          authentication, and file storage), an AI provider (content generation), and Stripe
          (payment processing). Your use of the Service is also subject to those providers'
          applicable terms.
        </p>
      </Section>

      <Section title="12. Disclaimer of Warranties">
        <p>
          The Service is provided "as is" and "as available" without warranties of any kind,
          express or implied, including fitness for a particular purpose, accuracy, or
          uninterrupted availability.
        </p>
      </Section>

      <Section title="13. Limitation of Liability">
        <p>
          To the maximum extent permitted by law, MyRecruiterCheck shall not be liable for any
          indirect, incidental, or consequential damages, or for any loss of income, opportunity,
          or data arising from your use of the Service. Our total liability for any claim shall not
          exceed the amount you paid us in the three months preceding the claim.
        </p>
      </Section>

      <Section title="14. Changes to These Terms">
        <p>
          We may update these Terms from time to time. Material changes will be reflected by
          updating the "Last updated" date above. Continued use of the Service after changes take
          effect constitutes acceptance of the revised Terms.
        </p>
      </Section>

      <Section title="15. Governing Law">
        <p>
          These Terms are governed by the laws of the Netherlands, without regard to conflict of law
          principles. Any disputes shall be submitted to the competent courts of the Netherlands,
          without prejudice to any mandatory consumer protection rights you may have in your country
          of residence.
        </p>
      </Section>

      <Section title="16. Contact">
        <p>
          Questions about these Terms can be sent to{' '}
          <a href="mailto:support@recruitercheck.app" className="font-medium text-blue hover:underline">
            support@recruitercheck.app
          </a>
          .
        </p>
      </Section>
    </LegalLayout>
  )
}
