-- Reconciles tracked migration history with the feedback table's actual,
-- long-standing production schema. Discovered while replaying every
-- tracked migration from scratch against an isolated test project for the
-- scoring rubric release: the initial_schema migration created
-- public.feedback with `summary text not null` and
-- `recruiter_perspective text not null` and no `prospects` column, but
-- production's real feedback table has never had those two columns and has
-- had a `prospects jsonb not null default '[]'` column for as long as the
-- analyze-check function has referenced it (confirmed directly against
-- production before writing this file) -- some earlier, untracked change
-- made this edit directly, without a corresponding migration file ever
-- being committed.
--
-- This migration reconciles a fresh environment (built purely from tracked
-- migrations, e.g. a new isolated test project) to match that real,
-- long-standing production shape. It is intentionally idempotent (IF
-- EXISTS / IF NOT EXISTS throughout) so it is a safe no-op when run against
-- production, where the schema already matches -- nothing here is applied
-- to production as part of this change; the migration is reviewed first.
--
-- Does not modify any other, already-applied migration file -- production
-- history is append only. This is purely additive reconciliation.
alter table public.feedback
  add column if not exists prospects jsonb not null default '[]'::jsonb;

alter table public.feedback
  drop column if exists summary;

alter table public.feedback
  drop column if exists recruiter_perspective;

comment on column public.feedback.prospects is
  'Up to two evidence based sentences on interview prospects, generated by analyze-check. See ScoreAwareProspects in logic.ts.';
